### ISSUE TITLE
Loading other TS files

### ISSUE THREAD

**Issue by toovy** [eduardonunesp/phaser-typescript-webpack-boilerplate#2]
Hello @eduardonunesp,

thanks for sharing your boilerplate, as I can see it really works well for a project kickoff. Nevertheless I'm having a issue that I don't know how to resolve. If I create new ts files in src, e.g. config.ts:

```
export default {
  width: 800,
  height: 600
}
```

And if I want to import it, I've got two options:

1) import Config from './config.ts'
2) import Config from './config'

Version 1 imports and compiles. But VSCode marks it as wrong and says [ts] An import path cannot end with a '.ts' extension. Consider importing './config' instead. I cannot use intellisense on the Config object.

Version 2 seems to be ok for VSCode, I can use intellisense, no errors. But webpack wont compile.

```
ERROR in ./src/index.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ./config in /Applications/MAMP/htdocs/temp/cubewarrs/src
 @ ./src/index.ts 8:15-34
```

Do you have any idea how to resolve this?

Thanks,
BR,
toovy

**Comment by eduardonunesp** [comment]
Hey thanks, interesting, looks like webpack cannot find the file properly. I'll take a look on that and try to reproduce the issue. If you have any update please let me know.

**Comment by eduardonunesp** [comment]
Ok the latest commit should solve our issue @toovy

**Comment by toovy** [comment]
@eduardonunesp ah, a doubled key in the config, I see. Tested, it works! Thanks for fixing it, I'll probably try it out soon!
