### ISSUE TITLE
npm build -- not working :(

### ISSUE THREAD

**Issue by SomeTallGy** [eduardonunesp/phaser-typescript-webpack-boilerplate#3]
Hello, I love your boilerplate, works in VSCode brilliantly.  however I can't seem to get a build to work.  I run 'npm run-script build' (as 'npm build' wasn't working) and i get a long list of warnings.  I run the index file in the dist folder, and nothing happens.

This is the log from my terminal from vscode:

`Barts-MacBook-Pro:phaser-typescript-webpack-boilerplate barthenderson$ sudo npm run-script build
Password:

> phaser-typescript-webpack-boilerplate@1.0.0 build /Users/barthenderson/LongGame/phaser-typescript-webpack-boilerplate
> rimraf ./dist && webpack -p

ts-loader: Using typescript@2.4.1 and /Users/barthenderson/LongGame/phaser-typescript-webpack-boilerplate/tsconfig.json
Hash: 4d8d973823daafbe0ecb
Version: webpack 1.15.0
Time: 18734ms
                      Asset       Size  Chunks             Chunk Names
             main.bundle.js     826 kB       0  [emitted]  main
         main.bundle.js.map    7.83 MB       0  [emitted]  main
assets/images/mushroom2.png    3.64 kB          [emitted]
                 index.html  237 bytes          [emitted]
    + 10 hidden modules

WARNING in ./~/phaser/build/custom/p2.js
Critical dependencies:
24:397-404 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/phaser/build/custom/p2.js 24:397-404

WARNING in main.bundle.js from UglifyJs
Side effects in initialization of unused variable game [./src/index.ts:60,8]
Boolean && always false [./~/phaser/build/custom/p2.js:24,60]
Condition always true [./~/phaser/build/custom/p2.js:24,13]
Dropping unreachable code [./~/phaser/build/custom/p2.js:24,60]
Declarations in unreachable code! [./~/phaser/build/custom/p2.js:24,116]
Dropping unused variable f [./~/phaser/build/custom/p2.js:24,116]
Dropping unused variable t [./~/phaser/build/custom/p2.js:905,0]
Side effects in initialization of unused variable Utils [./~/phaser/build/custom/p2.js:734,0]
Side effects in initialization of unused variable Circle [./~/phaser/build/custom/p2.js:1097,0]
Side effects in initialization of unused variable Plane [./~/phaser/build/custom/p2.js:1098,0]
Side effects in initialization of unused variable Shape [./~/phaser/build/custom/p2.js:1099,0]
Side effects in initialization of unused variable Particle [./~/phaser/build/custom/p2.js:1100,0]
Side effects in initialization of unused variable vec2 [./~/phaser/build/custom/p2.js:1102,0]
Side effects in initialization of unused variable bodyB [./~/phaser/build/custom/p2.js:1500,0]
Dropping unused variable centerDist [./~/phaser/build/custom/p2.js:2174,0]
Dropping unused variable convexToCircle [./~/phaser/build/custom/p2.js:2175,0]
Dropping unused variable orthoDist [./~/phaser/build/custom/p2.js:2176,0]
Dropping unused variable projectedPoint [./~/phaser/build/custom/p2.js:2177,0]
Dropping unused variable closestEdge [./~/phaser/build/custom/p2.js:2181,0]
Dropping unused variable closestEdgeDistance [./~/phaser/build/custom/p2.js:2182,0]
Dropping unused variable closestEdgeOrthoDist [./~/phaser/build/custom/p2.js:2183,0]
Dropping unused variable numReported [./~/phaser/build/custom/p2.js:2192,0]
Dropping unused variable orthoDist [./~/phaser/build/custom/p2.js:2385,0]
Dropping unused variable projectedPoint [./~/phaser/build/custom/p2.js:2386,0]
Dropping unused variable worldVertex [./~/phaser/build/custom/p2.js:2388,0]
Dropping unused variable closestEdge [./~/phaser/build/custom/p2.js:2389,0]
Dropping unused variable closestEdgeDistance [./~/phaser/build/custom/p2.js:2390,0]
Dropping unused variable closestEdgeOrthoDist [./~/phaser/build/custom/p2.js:2391,0]
Dropping unused variable r0 [./~/phaser/build/custom/p2.js:2393,0]
Dropping unused variable r1 [./~/phaser/build/custom/p2.js:2394,0]
Dropping unused variable localPoint [./~/phaser/build/custom/p2.js:2395,0]
Dropping unused variable numReported [./~/phaser/build/custom/p2.js:2400,0]
Dropping unused variable lastCross [./~/phaser/build/custom/p2.js:2414,0]
Side effects in initialization of unused variable d [./~/phaser/build/custom/p2.js:2434,0]
Dropping unused variable dst [./~/phaser/build/custom/p2.js:2781,0]
Dropping unused variable shapeB [./~/phaser/build/custom/p2.js:2841,0]
Dropping unused variable projected [./~/phaser/build/custom/p2.js:2915,0]
Dropping unused variable found [./~/phaser/build/custom/p2.js:3575,0]
Side effects in initialization of unused variable Utils [./~/phaser/build/custom/p2.js:1177,0]
Side effects in initialization of unused variable ContactEquation [./~/phaser/build/custom/p2.js:1182,0]
Side effects in initialization of unused variable FrictionEquation [./~/phaser/build/custom/p2.js:1183,0]
Side effects in initialization of unused variable Body [./~/phaser/build/custom/p2.js:1187,0]
Side effects in initialization of unused variable planeCapsule_tmp3 [./~/phaser/build/custom/p2.js:2752,0]
Side effects in initialization of unused variable from [./~/phaser/build/custom/p2.js:3848,0]
Side effects in initialization of unused variable to [./~/phaser/build/custom/p2.js:3849,0]
Side effects in initialization of unused variable RaycastResult [./~/phaser/build/custom/p2.js:3610,0]
Side effects in initialization of unused variable Shape [./~/phaser/build/custom/p2.js:3611,0]
Side effects in initialization of unused variable AABB [./~/phaser/build/custom/p2.js:3612,0]
Side effects in initialization of unused variable hitPointWorld [./~/phaser/build/custom/p2.js:3837,0]
Side effects in initialization of unused variable lower [./~/phaser/build/custom/p2.js:4212,0]
Side effects in initialization of unused variable upper [./~/phaser/build/custom/p2.js:4213,0]
Side effects in initialization of unused variable distance [./~/phaser/build/custom/p2.js:4556,0]
Side effects in initialization of unused variable Equation [./~/phaser/build/custom/p2.js:4637,0]
Side effects in initialization of unused variable vec2 [./~/phaser/build/custom/p2.js:4639,0]
Side effects in initialization of unused variable localAngleB [./~/phaser/build/custom/p2.js:4760,0]
Side effects in initialization of unused variable old [./~/phaser/build/custom/p2.js:5087,0]
Side effects in initialization of unused variable normal [./~/phaser/build/custom/p2.js:5445,0]
Side effects in initialization of unused variable tangent [./~/phaser/build/custom/p2.js:5446,0]
Side effects in initialization of unused variable vec2 [./~/phaser/build/custom/p2.js:5587,0]
Side effects in initialization of unused variable xi [./~/phaser/build/custom/p2.js:5936,0]
Side effects in initialization of unused variable xj [./~/phaser/build/custom/p2.js:5937,0]
Dropping unused variable ri [./~/phaser/build/custom/p2.js:6044,0]
Dropping unused variable rj [./~/phaser/build/custom/p2.js:6045,0]
Dropping unused variable Mdiag [./~/phaser/build/custom/p2.js:6050,0]
Side effects in initialization of unused variable Body [./~/phaser/build/custom/p2.js:5768,0]
Side effects in initialization of unused variable addToWlambda_ri [./~/phaser/build/custom/p2.js:6029,0]
Side effects in initialization of unused variable addToWlambda_rj [./~/phaser/build/custom/p2.js:6030,0]
Side effects in initialization of unused variable addToWlambda_Mdiag [./~/phaser/build/custom/p2.js:6031,0]
Side effects in initialization of unused variable bi [./~/phaser/build/custom/p2.js:6181,0]
Side effects in initialization of unused variable bj [./~/phaser/build/custom/p2.js:6182,0]
Side effects in initialization of unused variable Utils [./~/phaser/build/custom/p2.js:6089,0]
Side effects in initialization of unused variable vec2 [./~/phaser/build/custom/p2.js:6250,0]
Side effects in initialization of unused variable sleepState [./~/phaser/build/custom/p2.js:8529,0]
Side effects in initialization of unused variable Body_applyForce_r [./~/phaser/build/custom/p2.js:8200,0]
Side effects in initialization of unused variable adjustCenterOfMass_tmp1 [./~/phaser/build/custom/p2.js:8409,0]
Side effects in initialization of unused variable Utils [./~/phaser/build/custom/p2.js:8777,0]
Side effects in initialization of unused variable vec2 [./~/phaser/build/custom/p2.js:8945,0]
Side effects in initialization of unused variable vec2 [./~/phaser/build/custom/p2.js:9000,0]
Side effects in initialization of unused variable Utils [./~/phaser/build/custom/p2.js:9065,0]
Side effects in initialization of unused variable corner1 [./~/phaser/build/custom/p2.js:9432,0]
Side effects in initialization of unused variable corner2 [./~/phaser/build/custom/p2.js:9433,0]
Side effects in initialization of unused variable corner3 [./~/phaser/build/custom/p2.js:9434,0]
Side effects in initialization of unused variable corner4 [./~/phaser/build/custom/p2.js:9435,0]
Side effects in initialization of unused variable direction [./~/phaser/build/custom/p2.js:9574,0]
Dropping unused variable n [./~/phaser/build/custom/p2.js:10035,0]
Dropping unused variable ac [./~/phaser/build/custom/p2.js:10039,0]
Dropping unused variable ca [./~/phaser/build/custom/p2.js:10040,0]
Dropping unused variable cb [./~/phaser/build/custom/p2.js:10041,0]
Side effects in initialization of unused variable decomp [./~/phaser/build/custom/p2.js:9814,0]
Side effects in initialization of unused variable updateCenterOfMass_ac [./~/phaser/build/custom/p2.js:10021,0]
Side effects in initialization of unused variable updateCenterOfMass_ca [./~/phaser/build/custom/p2.js:10022,0]
Side effects in initialization of unused variable updateCenterOfMass_cb [./~/phaser/build/custom/p2.js:10023,0]
Side effects in initialization of unused variable updateCenterOfMass_n [./~/phaser/build/custom/p2.js:10024,0]
Side effects in initialization of unused variable direction [./~/phaser/build/custom/p2.js:10405,0]
Dropping unused variable hitPointWorld [./~/phaser/build/custom/p2.js:10407,0]
Dropping unused function getLineSegmentsIntersection [./~/phaser/build/custom/p2.js:10374,0]
Side effects in initialization of unused variable Utils [./~/phaser/build/custom/p2.js:10193,0]
Side effects in initialization of unused variable intersectHeightfield_hitPointWorld [./~/phaser/build/custom/p2.js:10365,0]
Side effects in initialization of unused variable intersectHeightfield_unit_y [./~/phaser/build/custom/p2.js:10371,0]
Side effects in initialization of unused variable raycast_hitPoint [./~/phaser/build/custom/p2.js:10501,0]
Dropping unused variable dir_scaled_with_t [./~/phaser/build/custom/p2.js:10682,0]
Dropping unused variable hitPoint [./~/phaser/build/custom/p2.js:10683,0]
Side effects in initialization of unused variable Utils [./~/phaser/build/custom/p2.js:10578,0]
Side effects in initialization of unused variable intersectPlane_dir_scaled_with_t [./~/phaser/build/custom/p2.js:10665,0]
Side effects in initialization of unused variable intersectPlane_hitPoint [./~/phaser/build/custom/p2.js:10666,0]
Side effects in initialization of unused variable add [./~/phaser/build/custom/p2.js:11048,0]
Side effects in initialization of unused variable set [./~/phaser/build/custom/p2.js:11049,0]
Dropping unused variable q [./~/phaser/build/custom/p2.js:11085,0]
Dropping unused variable B [./~/phaser/build/custom/p2.js:11085,0]
Side effects in initialization of unused variable Utils [./~/phaser/build/custom/p2.js:11204,0]
Side effects in initialization of unused variable currentObject [./~/phaser/build/custom/p2.js:11504,0]
Side effects in initialization of unused variable last [./~/phaser/build/custom/p2.js:11529,0]
Side effects in initialization of unused variable OverlapKeeperRecord [./~/phaser/build/custom/p2.js:11472,0]
Side effects in initialization of unused variable Utils [./~/phaser/build/custom/p2.js:11474,0]
Side effects in initialization of unused variable vec2 [./~/phaser/build/custom/p2.js:12083,0]
Side effects in initialization of unused variable Island [./~/phaser/build/custom/p2.js:12084,0]
Side effects in initialization of unused variable IslandNode [./~/phaser/build/custom/p2.js:12085,0]
Dropping unused variable that [./~/phaser/build/custom/p2.js:12898,0]
Dropping unused variable t0 [./~/phaser/build/custom/p2.js:12908,0]
Dropping unused variable t1 [./~/phaser/build/custom/p2.js:12908,0]
Dropping unused variable fhMinv [./~/phaser/build/custom/p2.js:12909,0]
Dropping unused variable velodt [./~/phaser/build/custom/p2.js:12910,0]
Side effects in initialization of unused variable scale [./~/phaser/build/custom/p2.js:12912,0]
Side effects in initialization of unused variable rotate [./~/phaser/build/custom/p2.js:12914,0]
Dropping unused variable zero [./~/phaser/build/custom/p2.js:13463,0]
Side effects in initialization of unused variable Solver [./~/phaser/build/custom/p2.js:12331,0]
Side effects in initialization of unused variable Ray [./~/phaser/build/custom/p2.js:12332,0]
Side effects in initialization of unused variable Line [./~/phaser/build/custom/p2.js:12336,0]
Side effects in initialization of unused variable Shape [./~/phaser/build/custom/p2.js:12342,0]
Side effects in initialization of unused variable LinearSpring [./~/phaser/build/custom/p2.js:12343,0]
Side effects in initialization of unused variable DistanceConstraint [./~/phaser/build/custom/p2.js:12346,0]
Side effects in initialization of unused variable Constraint [./~/phaser/build/custom/p2.js:12347,0]
Side effects in initialization of unused variable LockConstraint [./~/phaser/build/custom/p2.js:12348,0]
Side effects in initialization of unused variable RevoluteConstraint [./~/phaser/build/custom/p2.js:12349,0]
Side effects in initialization of unused variable PrismaticConstraint [./~/phaser/build/custom/p2.js:12350,0]
Side effects in initialization of unused variable GearConstraint [./~/phaser/build/custom/p2.js:12351,0]
Side effects in initialization of unused variable pkg [./~/phaser/build/custom/p2.js:12352,0]
Side effects in initialization of unused variable Broadphase [./~/phaser/build/custom/p2.js:12353,0]
Side effects in initialization of unused variable RotationalSpring [./~/phaser/build/custom/p2.js:12360,0]
Side effects in initialization of unused variable step_r [./~/phaser/build/custom/p2.js:12796,0]
Side effects in initialization of unused variable step_runit [./~/phaser/build/custom/p2.js:12797,0]
Side effects in initialization of unused variable step_u [./~/phaser/build/custom/p2.js:12798,0]
Side effects in initialization of unused variable step_f [./~/phaser/build/custom/p2.js:12799,0]
Side effects in initialization of unused variable step_fhMinv [./~/phaser/build/custom/p2.js:12800,0]
Side effects in initialization of unused variable step_velodt [./~/phaser/build/custom/p2.js:12801,0]
Side effects in initialization of unused variable zero [./~/phaser/build/custom/p2.js:12805,0]
Side effects in initialization of unused variable interpvelo [./~/phaser/build/custom/p2.js:12806,0]
Side effects in initialization of unused variable hitTest_zero [./~/phaser/build/custom/p2.js:13441,0]
Dropping unused variable define [./~/phaser/build/custom/p2.js:24,251]
Dropping unused variable module [./~/phaser/build/custom/p2.js:24,251]
Dropping unused variable exports [./~/phaser/build/custom/p2.js:24,251]
Dropping unreachable code [./~/phaser/build/custom/phaser-split.js:52083,0]
Dropping unreachable code [./~/phaser/build/custom/phaser-split.js:72358,0]
Condition always true [./~/phaser/build/custom/phaser-split.js:80344,0]
Dropping unreachable code [./~/phaser/build/custom/phaser-split.js:80349,5]
Dropping unused variable root [./~/phaser/build/custom/phaser-split.js:38,0]
Condition always true [./~/phaser/build/custom/pixi.js:9109,0]
Dropping unreachable code [./~/phaser/build/custom/pixi.js:9114,5]
Dropping unused variable root [./~/phaser/build/custom/pixi.js:36,0]
Child html-webpack-plugin for "index.html":
        + 3 hidden modules
Barts-MacBook-Pro:phaser-typescript-webpack-boilerplate barthenderson$`

**Comment by eduardonunesp** [comment]
As I said before, check you `localhost 9000`, if isn't in use. You can use the port 9001 changing it in the `package.json` file. If you see any problem regarding the path of files, make sure you downloaded all necessary files.

**Comment by SomeTallGy** [comment]
The localhost 9000 fix was for another issue, I believe this is a different cause -- [Edit] : found that there was a Dom issue with local files I was seeing.  This is now working as intended I believe.

**Comment by SomeTallGy** [comment]
With that said, the build is being created fine -- it was just an internal security issue i was seeing.  Thanks for your help!
